name: External link check

on:
  schedule:
    - cron: "17 8 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: external-links-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-link-check:
    uses: alawein/.github/.github/workflows/check-links.yml@6f6dbe7f3a23ab830a32007bb52b83fd1bb40563 # v1.2.0
    with:
      offline: false
